import docker
import os

client = docker.from_env()
CONTAINER_NAME = "my_agent_sandbox"


def run_code_in_sandbox(code_content: str, filename: str = "script.py", timeout: int = 5):
    try:
        container = client.containers.get(CONTAINER_NAME)
    except docker.errors.NotFound:
        return "Error: Sandbox container is not running."

    # 1. Write the agent's code into the container's workspace
    # We use 'bash -c' to echo the string into a file inside the tmpfs
    escaped_code = code_content.replace("'", "'\\''")
    write_command = f"cat << 'EOF' > /workspace/{filename}\n{code_content}\nEOF"

    container.exec_run(cmd=f"bash -c '{write_command}'", user="agentuser")

    # 2. Execute the code and capture stdout/stderr
    # We wrap it in a timeout mechanism in case of infinite loops
    exec_command = f"python /workspace/{filename}"

    # exec_run doesn't natively support timeouts, so we use a bash timeout trick
    secure_exec = f"timeout {timeout} {exec_command}"

    result = container.exec_run(cmd=secure_exec, user="agentuser")

    # 3. Decode and return the output
    output = result.output.decode("utf-8")

    if result.exit_code == 124:
        return f"Error: Code execution timed out after {timeout} seconds."

    return output


# --- SIMULATION OF YOUR AGENT LOOP ---
if __name__ == "__main__":
    # Example 1: Safe code generated by your LLM
    agent_code = """
def greet(name):
    return f"Hello, {name}! Your sandbox works."

print(greet("University Project"))
"""
    print("--- Running Agent Code ---")
    response = run_code_in_sandbox(agent_code)
    print(response)

    # Example 2: Malicious/Broken code simulation
    bad_code = """
import os
print("Trying to see root files:")
print(os.listdir('/'))
print("Trying to break things:")
os.system('rm -rf /etc')
"""
    print("--- Running Malicious Code Simulation ---")
    response_bad = run_code_in_sandbox(bad_code)
    print(response_bad)